/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import java.io.File;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.filechooser.FileSystemView;
import org.apache.poi.xwpf.usermodel.UnderlinePatterns;
import static pack.Dashboard.flag;
import static pack.Dashboard.indexes;
import static pack.Dashboard.searchIndex;

/**
 *
 * @author Justine
 */
public class Clearance extends javax.swing.JFrame {

    private static File home = FileSystemView.getFileSystemView().getHomeDirectory();
    private static String DIR = home.getAbsolutePath();
    String name = "justine", address = "";
    int age;
    String bday = "";

    Date dat = new Date();
    SimpleDateFormat sf = new SimpleDateFormat("MMMM dd, yyyy");
    String date = sf.format(dat);

    /**
     * Creates new form Clearance
     */
    public Clearance() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Barangay Clearance");

        if (flag == false) {
            name = Variables.Fullname.get(searchIndex);
            bday = (String) Variables.Birthday.get(searchIndex);
            address = (String) Variables.FullAddress.get(searchIndex);

        } else {
            name = Variables.Fullname.get(indexes.get(searchIndex));
            bday = (String) Variables.Birthday.get(indexes.get(searchIndex));
            address = (String) Variables.FullAddress.get(indexes.get(searchIndex));
        }

        int bdayD = Integer.parseInt((String) bday.subSequence(bday.length() - 4, bday.length()));
        int currentD = Integer.parseInt((String) date.subSequence(date.length() - 4, date.length()));

        age = currentD - bdayD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toExample = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        purposeText = new javax.swing.JTextField();
        remarkText = new javax.swing.JTextField();
        residenceText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toExample.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        toExample.setForeground(new java.awt.Color(153, 153, 153));
        toExample.setText("Ex. For Legal Purposes");
        getContentPane().add(toExample, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Remarks:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Residence Certificate Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Purpose:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 157, 25));

        purposeText.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        purposeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                purposeTextKeyTyped(evt);
            }
        });
        getContentPane().add(purposeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 42, 540, 34));

        remarkText.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        remarkText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remarkTextKeyTyped(evt);
            }
        });
        getContentPane().add(remarkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 540, 34));

        residenceText.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        residenceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                residenceTextKeyTyped(evt);
            }
        });
        getContentPane().add(residenceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 540, 34));

        jButton1.setText("Okay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 90, 40));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void purposeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purposeTextKeyTyped
        toExample.setVisible(false);

        if (purposeText.getText().equals("")) {
            toExample.setVisible(true);
        }
    }//GEN-LAST:event_purposeTextKeyTyped

    private void remarkTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remarkTextKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_remarkTextKeyTyped

    private void residenceTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_residenceTextKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_residenceTextKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!purposeText.getText().equals("") && !remarkText.getText().equals("") && !residenceText.getText().equals("")) {
            try {
                FileOutputStream outStream = new FileOutputStream(home.getAbsolutePath() + "\\BarangayClearance.docx");
                XWPFDocument doc = new XWPFDocument();

//            InputStream pic = new FileInputStream("C:\\Users\\carlj\\Desktop\\staIlenaLogo.png");
//            byte [] picbytes = IOUtils.toByteArray(pic);
//            doc.addPictureData(picbytes, Document.PICTURE_TYPE_PNG);
                XWPFParagraph para = doc.createParagraph();
                para.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun paraRun = para.createRun();

                paraRun.setBold(true);
                paraRun.setFontSize(12);
                paraRun.setFontFamily("Times New Roman");
                paraRun.setText("Republic of the Philippines");
                paraRun.addBreak();
                paraRun.setText("Province of Bulacan");
                paraRun.addBreak();
                paraRun.setText("Municipality of Hagonoy");
                paraRun.addBreak();
                paraRun.setText("Barangay Sta. Elena");
                paraRun.addBreak();
                paraRun.setText("Landline : 794 - 0541");

                XWPFParagraph para2 = doc.createParagraph();
                para2.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun paraRun2 = para2.createRun();

                paraRun2.setBold(true);
                paraRun2.setFontSize(15);
                paraRun2.setFontFamily("Times New Roman");
                paraRun2.setText("OFFICE OF THE BARANGAY CAPTAIN");

                XWPFParagraph para3 = doc.createParagraph();
                para3.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun3 = para3.createRun();

                paraRun3.setBold(false);
                paraRun3.setFontSize(10);
                paraRun3.setFontFamily("Times New Roman");
                paraRun3.setText("==================================================================================");

                XWPFParagraph para4 = doc.createParagraph();
                para4.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun paraRun4 = para4.createRun();

                paraRun4.setBold(true);
                paraRun4.setFontSize(13);
                paraRun4.setFontFamily("Times New Roman");
                paraRun4.setText("CERTIFICATION");

                XWPFParagraph para5 = doc.createParagraph();
                para5.setAlignment(ParagraphAlignment.LEFT);
                para5.setFirstLineIndent(300);
                XWPFRun paraRun5 = para5.createRun();

                paraRun5.setBold(false);
                paraRun5.setFontSize(12);
                paraRun5.setFontFamily("Times New Roman");
                paraRun5.setText("This is to certify that the person whose name and thumb mark appears herein has\n"
                        + "requested for a record and Barangay Clearance from this office and the result are stated here in below:  ");

                XWPFParagraph para6 = doc.createParagraph();
                para6.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun6 = para6.createRun();

                paraRun6.setBold(true);
                paraRun6.setFontSize(13);
                paraRun6.setFontFamily("Times New Roman");
                paraRun6.setText("Name                : " + name);
                paraRun6.addBreak();
                paraRun6.setText("Address            : " + address);
                paraRun6.addBreak();
                paraRun6.setText("Date of Birth    : " + bday);
                paraRun6.addBreak();
                paraRun6.setText("Place of Birth   : Hagonoy,Bulacan");
                paraRun6.addBreak();
                paraRun6.setText("Purpose            : " + purposeText.getText());

                XWPFParagraph para7 = doc.createParagraph();
                para7.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun paraRun7 = para7.createRun();

                paraRun7.setBold(false);
                paraRun7.setFontSize(12);
                paraRun7.setFontFamily("Times New Roman");
                paraRun7.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
                paraRun7.addBreak();
                paraRun7.addBreak();
                paraRun7.setText("REMARKS:  " + remarkText.getText());
                paraRun7.addBreak();
                paraRun7.addBreak();
                paraRun7.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

                XWPFParagraph para8 = doc.createParagraph();
                para8.setAlignment(ParagraphAlignment.LEFT);
                para8.setIndentationLeft(4);
                XWPFRun paraRun8 = para8.createRun();

                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("EEE, MMMM dd, yyyy");
                String date = s.format(d);

                paraRun8.setBold(false);
                paraRun8.setFontSize(12);
                paraRun8.setFontFamily("Times New Roman");
                paraRun8.addBreak();
                paraRun8.setText("Exhibiting his / her Residence Certificate No.: " + residenceText.getText());
                paraRun8.addBreak();
                paraRun8.setText("Done this " + date);

                XWPFParagraph para9 = doc.createParagraph();
                para9.setAlignment(ParagraphAlignment.LEFT);
                para9.setFirstLineIndent(300);
                XWPFRun paraRun9 = para9.createRun();

                paraRun9.setBold(true);
                paraRun9.setFontSize(12);
                paraRun9.setFontFamily("Times New Roman");
                paraRun9.setText("Note: This Clearance is valid for one(1) year after the date issued.\n"
                        + "	Not Valid if there is no dry Seal.");

                XWPFParagraph para10 = doc.createParagraph();
                para10.setAlignment(ParagraphAlignment.RIGHT);
                XWPFRun paraRun10 = para10.createRun();

                paraRun10.setBold(true);
                paraRun10.setFontSize(12);
                paraRun10.setFontFamily("Times New Roman");
                paraRun10.setText("_______________");
                paraRun10.addBreak();
                paraRun10.setText("|                             |");
                paraRun10.addBreak();
                paraRun10.setText("|                             |");
                paraRun10.addBreak();
                paraRun10.setText("|                             |");
                paraRun10.addBreak();
                paraRun10.setText("|                             |");
                paraRun10.addBreak();
                paraRun10.setText("|                             |");
                paraRun10.addBreak();
                paraRun10.setText("¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯");
                paraRun10.addBreak();
                paraRun10.setText("Right Thumb Mark");

                XWPFParagraph para11 = doc.createParagraph();
                para11.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun11 = para11.createRun();

                paraRun11.setBold(true);
                paraRun11.setFontSize(13);
                paraRun11.setFontFamily("Times New Roman");
                paraRun11.setText("______________________");
                paraRun11.addBreak();
                paraRun11.setText("DOROTEO M. REYES III                                                         " + name);

                XWPFParagraph para12 = doc.createParagraph();
                para12.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun12 = para12.createRun();

                paraRun12.setBold(false);
                paraRun12.setFontSize(12);
                paraRun12.setFontFamily("Times New Roman");
                paraRun12.setText("        Barangay Captain                                                                    Signature Over Printed Name");

                doc.write(outStream);
                outStream.close();
                //pic.close();
                JOptionPane.showMessageDialog(null, "Document created.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

            Desktop desktop = Desktop.getDesktop();
            try {
                File f = new File(DIR + "\\BarangayClearance.docx");
                desktop.open(f);  // opens application (MSWord) associated with .doc file
            } catch (Exception ex) {
                // WordDocument.this is to refer to outer class's instance from inner class
                JOptionPane.showMessageDialog(Clearance.this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please, Fill up all fields.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clearance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clearance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField purposeText;
    private javax.swing.JTextField remarkText;
    private javax.swing.JTextField residenceText;
    private javax.swing.JLabel toExample;
    // End of variables declaration//GEN-END:variables
}
