/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import java.io.File;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.filechooser.FileSystemView;
import org.apache.poi.xwpf.usermodel.UnderlinePatterns;
import static pack.Dashboard.flag;
import static pack.Dashboard.indexes;
import static pack.Dashboard.searchIndex;

/**
 *
 * @author Justine
 */
public class Indigency extends javax.swing.JFrame {

    private static File home = FileSystemView.getFileSystemView().getHomeDirectory();
    private static String DIR = home.getAbsolutePath();
    String name = "";
    int age;
    String bday = "";

    Date dat = new Date();
    SimpleDateFormat sf = new SimpleDateFormat("MMMM dd, yyyy");
    String date = sf.format(dat);

    /**
     * Creates new form Indigency
     */
    public Indigency() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Indigecy");
        purposeText.setLineWrap(true);

        if (flag == false) {
            name = Variables.Fullname.get(searchIndex);
            bday = (String) Variables.Birthday.get(searchIndex);

        } else {
            name = Variables.Fullname.get(indexes.get(searchIndex));
            bday = (String) Variables.Birthday.get(indexes.get(searchIndex));
        }

        int bdayD = Integer.parseInt((String) bday.subSequence(bday.length() - 4, bday.length()));
        int currentD = Integer.parseInt((String) date.subSequence(date.length() - 4, date.length()));

        age = currentD - bdayD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        toExample = new javax.swing.JLabel();
        purposeExample = new javax.swing.JLabel();
        toText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purposeText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("To:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("To:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 157, 25));

        toExample.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        toExample.setForeground(new java.awt.Color(153, 153, 153));
        toExample.setText("Mayor Raulito T. Manlapaz Sr.");
        getContentPane().add(toExample, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 40));

        purposeExample.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        purposeExample.setForeground(new java.awt.Color(153, 153, 153));
        purposeExample.setText("State the purpose of Indigency.");
        getContentPane().add(purposeExample, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 30));

        toText.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        toText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toTextKeyTyped(evt);
            }
        });
        getContentPane().add(toText, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 42, 540, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Purpose:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 157, 25));

        purposeText.setColumns(20);
        purposeText.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        purposeText.setRows(5);
        purposeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                purposeTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(purposeText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 118, 540, 267));

        jButton1.setText("Okay");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 90, 40));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 90, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toTextKeyTyped
        toExample.setVisible(false);

        if (toText.getText().equals("")) {
            toExample.setVisible(true);
        }
    }//GEN-LAST:event_toTextKeyTyped

    private void purposeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purposeTextKeyTyped
        purposeExample.setVisible(false);

        if (purposeText.getText().equals("")) {
            purposeExample.setVisible(true);
        }
    }//GEN-LAST:event_purposeTextKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!toText.getText().equals("") && !purposeText.getText().equals("")) {
            try {
                FileOutputStream outStream = new FileOutputStream(home.getAbsolutePath() + "\\IndigencyCert.docx");
                XWPFDocument doc = new XWPFDocument();

//            InputStream pic = new FileInputStream("C:\\Users\\carlj\\Desktop\\staIlenaLogo.png");
//            byte [] picbytes = IOUtils.toByteArray(pic);
//            doc.addPictureData(picbytes, Document.PICTURE_TYPE_PNG);
                XWPFParagraph para = doc.createParagraph();
                para.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun paraRun = para.createRun();

                paraRun.setBold(true);
                paraRun.setFontSize(12);
                paraRun.setFontFamily("Times New Roman");
                paraRun.setText("Republic of the Philippines");
                paraRun.addBreak();
                paraRun.setText("Province of Bulacan");
                paraRun.addBreak();
                paraRun.setText("Municipality of Hagonoy");
                paraRun.addBreak();
                paraRun.setText("Barangay Sta. Elena");
                paraRun.addBreak();

                XWPFParagraph para2 = doc.createParagraph();
                para2.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun2 = para2.createRun();

                paraRun2.setBold(true);
                paraRun2.setFontSize(13);
                paraRun2.setFontFamily("Times New Roman");
                paraRun2.setText("DOROTEO M. REYES III                                                      Telephone#: 794-0541");

                XWPFParagraph para3 = doc.createParagraph();
                para3.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun3 = para3.createRun();

                paraRun3.setBold(false);
                paraRun3.setFontSize(13);
                paraRun3.setFontFamily("Times New Roman");
                paraRun3.setText("BARANGAY CAPTAIN");
                paraRun3.addBreak();
                paraRun3.setText("=============================================================");

                XWPFParagraph para4 = doc.createParagraph();
                para4.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun paraRun4 = para4.createRun();

                paraRun4.setBold(true);
                paraRun4.setFontSize(17);
                paraRun4.setFontFamily("Times New Roman");
                paraRun4.setText("OFFICE OF THE BARANGAY CAPTAIN");
                paraRun4.addBreak();
                paraRun4.setText("BARANGAY OF STA. ILENA");

                XWPFParagraph para5 = doc.createParagraph();
                para5.setAlignment(ParagraphAlignment.RIGHT);
                XWPFRun paraRun5 = para5.createRun();

                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("EEE, MMMM dd, yyyy");
                String date = s.format(d);

                paraRun5.setBold(false);
                paraRun5.setFontSize(12);
                paraRun5.setFontFamily("Times New Roman");
                paraRun5.setUnderline(UnderlinePatterns.SINGLE);
                paraRun5.setText(date);

                XWPFParagraph para6 = doc.createParagraph();
                para6.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun6 = para6.createRun();

                paraRun6.setBold(false);
                paraRun6.setFontSize(12);
                paraRun6.setFontFamily("Times New Roman");
                paraRun6.setText("                                                                                                                                        Date");

                XWPFParagraph para7 = doc.createParagraph();
                para7.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun7 = para7.createRun();

                paraRun7.setBold(false);
                paraRun7.setFontSize(12);
                paraRun7.setFontFamily("Times New Roman");
                paraRun7.setText("Dear, " + toText.getText());

                XWPFParagraph para8 = doc.createParagraph();
                para8.setAlignment(ParagraphAlignment.LEFT);
                para8.setFirstLineIndent(300);
                XWPFRun paraRun8 = para8.createRun();

                paraRun8.setBold(false);
                paraRun8.setFontSize(12);
                paraRun8.setFontFamily("Times New Roman");
                paraRun8.setText("This is to certify that " + name + "," + age + " years  of age a resident of this barangay is found indigent and belong to poverty stricken family");

                XWPFParagraph para9 = doc.createParagraph();
                para9.setAlignment(ParagraphAlignment.LEFT);
                para9.setIndentationLeft(4);
                XWPFRun paraRun9 = para9.createRun();

                paraRun9.setBold(false);
                paraRun9.setFontSize(12);
                paraRun9.setFontFamily("Times New Roman");
                paraRun9.setText(purposeText.getText());

                XWPFParagraph para10 = doc.createParagraph();
                para10.setAlignment(ParagraphAlignment.LEFT);
                para10.setFirstLineIndent(300);
                XWPFRun paraRun10 = para10.createRun();

                paraRun10.setBold(false);
                paraRun10.setFontSize(12);
                paraRun10.setFontFamily("Times New Roman");
                paraRun10.setText("This certification is issued upon request of aboved – named person to be used for all legal intents and purposes.");

                XWPFParagraph para11 = doc.createParagraph();
                para11.setAlignment(ParagraphAlignment.RIGHT);
                XWPFRun paraRun11 = para11.createRun();

                paraRun11.setBold(true);
                paraRun11.setFontSize(13);
                paraRun11.setFontFamily("Times New Roman");
                paraRun11.setText("______________________");
                paraRun11.addBreak();
                paraRun11.setText("DOROTEO M. REYES III");

                XWPFParagraph para12 = doc.createParagraph();
                para12.setAlignment(ParagraphAlignment.LEFT);
                XWPFRun paraRun12 = para12.createRun();

                paraRun12.setBold(false);
                paraRun12.setFontSize(12);
                paraRun12.setFontFamily("Times New Roman");
                paraRun12.setText("                                                                                                                      Barangay Captain");

                XWPFParagraph para13 = doc.createParagraph();
                para13.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun paraRun13 = para13.createRun();

                paraRun13.setBold(false);
                paraRun13.setItalic(true);
                paraRun13.setFontSize(13);
                paraRun13.setFontFamily("Times New Roman");
                paraRun13.setText("NOT VALID WITHOUT DRY SEAL");

                doc.write(outStream);
                outStream.close();
                //pic.close();
                JOptionPane.showMessageDialog(null, "Document created.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

            Desktop desktop = Desktop.getDesktop();
            try {
                File f = new File(DIR + "\\IndigencyCert.docx");
                desktop.open(f);  // opens application (MSWord) associated with .doc file
            } catch (Exception ex) {
                // WordDocument.this is to refer to outer class's instance from inner class
                JOptionPane.showMessageDialog(Indigency.this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please, Fill up all fields.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indigency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indigency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indigency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indigency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Indigency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel purposeExample;
    private javax.swing.JTextArea purposeText;
    private javax.swing.JLabel toExample;
    private javax.swing.JTextField toText;
    // End of variables declaration//GEN-END:variables
}
